import { Legality } from "./card.interface";

export const Cards = [
  {
    id: "sv4pt5-236",
    name: "Clive",
    supertype: "Trainer",
    subtypes: ["Supporter"],
    rules: [
      "Your opponent reveals their hand, and you draw 2 cards for each Supporter card you find there.",
      "You may play only 1 Supporter card during your turn.",
    ],
    set: {
      id: "sv4pt5",
      name: "Paldean Fates",
      series: "Scarlet & Violet",
      printedTotal: 91,
      total: 245,
      legalities: {
        unlimited: Legality.LEGAL,
        standard: Legality.LEGAL,
        expanded: Legality.LEGAL,
      },
      releaseDate: "2024/01/26",
      updatedAt: "2024/01/25 15:00:00",
      images: {
        symbol: "https://images.pokemontcg.io/sv4pt5/symbol.png",
        logo: "https://images.pokemontcg.io/sv4pt5/logo.png",
      },
    },
    number: "236",
    artist: "Taiga Kayama",
    rarity: "Special Illustration Rare",
    legalities: {
      unlimited: Legality.LEGAL,
      standard: Legality.LEGAL,
      expanded: Legality.LEGAL,
    },
    images: {
      small: "https://images.pokemontcg.io/sv4pt5/236.png",
      large: "https://images.pokemontcg.io/sv4pt5/236_hires.png",
    },
    tcgplayer: {
      url: "https://prices.pokemontcg.io/tcgplayer/sv4pt5-236",
      updatedAt: "2024/02/03",
      prices: {
        holofoil: {
          low: 15.0,
          mid: 20.0,
          high: 55.0,
          market: 16.19,
          directLow: null,
        },
      },
    },
    cardmarket: {
      url: "https://prices.pokemontcg.io/cardmarket/sv4pt5-236",
      updatedAt: "2024/02/03",
      prices: {
        averageSellPrice: 19.14,
        lowPrice: 12.95,
        trendPrice: 8.67,
        germanProLow: 0.0,
        suggestedPrice: 0.0,
        reverseHoloSell: 0.0,
        reverseHoloLow: 0.0,
        reverseHoloTrend: 0.0,
        lowPriceExPlus: 12.99,
        avg1: 16.2,
        avg7: 18.86,
        avg30: 18.86,
        reverseHoloAvg1: 0.0,
        reverseHoloAvg7: 0.0,
        reverseHoloAvg30: 0.0,
      },
    },
  },
  {
    id: "sv4pt5-227",
    name: "Clive",
    supertype: "Trainer",
    subtypes: ["Supporter"],
    rules: [
      "Your opponent reveals their hand, and you draw 2 cards for each Supporter card you find there.",
      "You may play only 1 Supporter card during your turn.",
    ],
    set: {
      id: "sv4pt5",
      name: "Paldean Fates",
      series: "Scarlet & Violet",
      printedTotal: 91,
      total: 245,
      legalities: {
        unlimited: Legality.LEGAL,
        standard: Legality.LEGAL,
        expanded: Legality.LEGAL,
      },
      releaseDate: "2024/01/26",
      updatedAt: "2024/01/25 15:00:00",
      images: {
        symbol: "https://images.pokemontcg.io/sv4pt5/symbol.png",
        logo: "https://images.pokemontcg.io/sv4pt5/logo.png",
      },
    },
    number: "227",
    artist: "GOSSAN",
    rarity: "Ultra Rare",
    legalities: {
      unlimited: Legality.LEGAL,
      standard: Legality.LEGAL,
      expanded: Legality.LEGAL,
    },
    images: {
      small: "https://images.pokemontcg.io/sv4pt5/227.png",
      large: "https://images.pokemontcg.io/sv4pt5/227_hires.png",
    },
    tcgplayer: {
      url: "https://prices.pokemontcg.io/tcgplayer/sv4pt5-227",
      updatedAt: "2024/02/03",
      prices: {
        holofoil: {
          low: 0.43,
          mid: 1.03,
          high: 10.73,
          market: 0.68,
          directLow: null,
        },
      },
    },
    cardmarket: {
      url: "https://prices.pokemontcg.io/cardmarket/sv4pt5-227",
      updatedAt: "2024/02/03",
      prices: {
        averageSellPrice: 2.04,
        lowPrice: 0.89,
        trendPrice: 1.72,
        germanProLow: 0.0,
        suggestedPrice: 0.0,
        reverseHoloSell: 0.0,
        reverseHoloLow: 0.0,
        reverseHoloTrend: 0.0,
        lowPriceExPlus: 0.89,
        avg1: 1.7,
        avg7: 1.99,
        avg30: 1.99,
        reverseHoloAvg1: 0.0,
        reverseHoloAvg7: 0.0,
        reverseHoloAvg30: 0.0,
      },
    },
  },
  {
    id: "sv4pt5-201",
    name: "Ditto",
    supertype: "Pokémon",
    subtypes: ["Basic"],
    hp: "60",
    types: ["Colorless"],
    retreatCost: ["Colorless"],
    convertedRetreatCost: 1,
    set: {
      id: "sv4pt5",
      name: "Paldean Fates",
      series: "Scarlet & Violet",
      printedTotal: 91,
      total: 245,
      legalities: {
        unlimited: Legality.LEGAL,
        standard: Legality.LEGAL,
        expanded: Legality.LEGAL,
      },
      releaseDate: "2024/01/26",
      updatedAt: "2024/01/25 15:00:00",
      images: {
        symbol: "https://images.pokemontcg.io/sv4pt5/symbol.png",
        logo: "https://images.pokemontcg.io/sv4pt5/logo.png",
      },
    },
    number: "201",
    artist: "0313",
    rarity: "Shiny Rare",
    flavorText:
      "Its transformation ability is perfect. However, if made to laugh, it can't maintain its disguise.",
    nationalPokedexNumbers: [132],
    legalities: {
      unlimited: Legality.LEGAL,
      standard: Legality.LEGAL,
      expanded: Legality.LEGAL,
    },
    images: {
      small: "https://images.pokemontcg.io/sv4pt5/201.png",
      large: "https://images.pokemontcg.io/sv4pt5/201_hires.png",
    },
    tcgplayer: {
      url: "https://prices.pokemontcg.io/tcgplayer/sv4pt5-201",
      updatedAt: "2024/02/03",
      prices: {
        holofoil: {
          low: 28.5,
          mid: 29.5,
          high: 29.99,
          market: 9.29,
          directLow: null,
        },
      },
    },
    cardmarket: {
      url: "https://prices.pokemontcg.io/cardmarket/sv4pt5-201",
      updatedAt: "2024/02/03",
      prices: {
        averageSellPrice: 6.35,
        lowPrice: 5.7,
        trendPrice: 5.53,
        germanProLow: 0.0,
        suggestedPrice: 0.0,
        reverseHoloSell: 0.0,
        reverseHoloLow: 0.0,
        reverseHoloTrend: 0.0,
        lowPriceExPlus: 5.7,
        avg1: 6.88,
        avg7: 6.4,
        avg30: 6.4,
        reverseHoloAvg1: 0.0,
        reverseHoloAvg7: 0.0,
        reverseHoloAvg30: 0.0,
      },
    },
  },
  {
    id: "sv4pt5-5",
    name: "Toedscruel ex",
    supertype: "Pokémon",
    subtypes: ["Stage 1", "ex"],
    hp: "270",
    types: ["Grass"],
    rules: [
      "Pokémon ex rule: When your Pokémon ex is Knocked Out, your opponent takes 2 Prize cards.",
    ],
    retreatCost: ["Colorless", "Colorless"],
    convertedRetreatCost: 2,
    set: {
      id: "sv4pt5",
      name: "Paldean Fates",
      series: "Scarlet & Violet",
      printedTotal: 91,
      total: 245,
      legalities: {
        unlimited: Legality.LEGAL,
        standard: Legality.LEGAL,
        expanded: Legality.LEGAL,
      },
      releaseDate: "2024/01/26",
      updatedAt: "2024/01/25 15:00:00",
      images: {
        symbol: "https://images.pokemontcg.io/sv4pt5/symbol.png",
        logo: "https://images.pokemontcg.io/sv4pt5/logo.png",
      },
    },
    number: "5",
    artist: "5ban Graphics",
    rarity: "Double Rare",
    nationalPokedexNumbers: [949],
    legalities: {
      unlimited: Legality.LEGAL,
      standard: Legality.LEGAL,
      expanded: Legality.LEGAL,
    },
    images: {
      small: "https://images.pokemontcg.io/sv4pt5/5.png",
      large: "https://images.pokemontcg.io/sv4pt5/5_hires.png",
    },
    tcgplayer: {
      url: "https://prices.pokemontcg.io/tcgplayer/sv4pt5-5",
      updatedAt: "2024/02/03",
      prices: {
        holofoil: {
          low: 0.13,
          mid: 0.49,
          high: 7.48,
          market: 0.36,
          directLow: null,
        },
      },
    },
    cardmarket: {
      url: "https://prices.pokemontcg.io/cardmarket/sv4pt5-5",
      updatedAt: "2024/02/03",
      prices: {
        averageSellPrice: 0.87,
        lowPrice: 0.15,
        trendPrice: 0.7,
        germanProLow: 0.0,
        suggestedPrice: 0.0,
        reverseHoloSell: 0.0,
        reverseHoloLow: 0.0,
        reverseHoloTrend: 0.0,
        lowPriceExPlus: 0.15,
        avg1: 0.7,
        avg7: 0.88,
        avg30: 0.88,
        reverseHoloAvg1: 0.0,
        reverseHoloAvg7: 0.0,
        reverseHoloAvg30: 0.0,
      },
    },
  },
  {
    id: "sv4-184",
    name: "Dottler",
    supertype: "Pokémon",
    subtypes: ["Stage 1"],
    hp: "80",
    types: ["Grass"],
    evolvesTo: ["Orbeetle"],
    retreatCost: ["Colorless", "Colorless"],
    convertedRetreatCost: 2,
    set: {
      id: "sv4",
      name: "Paradox Rift",
      series: "Scarlet & Violet",
      printedTotal: 182,
      total: 266,
      legalities: {
        unlimited: Legality.LEGAL,
        standard: Legality.LEGAL,
        expanded: Legality.LEGAL,
      },
      releaseDate: "2023/11/03",
      updatedAt: "2023/11/03 15:00:00",
      images: {
        symbol: "https://images.pokemontcg.io/sv4/symbol.png",
        logo: "https://images.pokemontcg.io/sv4/logo.png",
      },
    },
    number: "184",
    artist: "Tetsu Kayama",
    rarity: "Illustration Rare",
    flavorText:
      "As it grows inside its shell, it uses its psychic abilities to monitor the outside world and prepare for evolution.",
    nationalPokedexNumbers: [825],
    legalities: {
      unlimited: Legality.LEGAL,
      standard: Legality.LEGAL,
      expanded: Legality.LEGAL,
    },
    images: {
      small: "https://images.pokemontcg.io/sv4/184.png",
      large: "https://images.pokemontcg.io/sv4/184_hires.png",
    },
    tcgplayer: {
      url: "https://prices.pokemontcg.io/tcgplayer/sv4-184",
      updatedAt: "2024/02/03",
      prices: {
        holofoil: {
          low: 0.99,
          mid: 1.99,
          high: 9.98,
          market: 1.58,
          directLow: 2.0,
        },
      },
    },
    cardmarket: {
      url: "https://prices.pokemontcg.io/cardmarket/sv4-184",
      updatedAt: "2024/02/03",
      prices: {
        averageSellPrice: 3.48,
        lowPrice: 1.99,
        trendPrice: 3.35,
        germanProLow: 0.0,
        suggestedPrice: 0.0,
        reverseHoloSell: 0.0,
        reverseHoloLow: 0.0,
        reverseHoloTrend: 0.0,
        lowPriceExPlus: 1.99,
        avg1: 2.94,
        avg7: 3.12,
        avg30: 3.42,
        reverseHoloAvg1: 0.0,
        reverseHoloAvg7: 0.0,
        reverseHoloAvg30: 0.0,
      },
    },
  },
];
